name: run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install aiomysql pymysql selenium requests futures eventlet
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: sleep 10  # 给MySQL服务足够时间启动

      - name: Run run.py
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: your_username
          DB_PASSWORD: YES
          DB_NAME: testdb
        run: python ${{ github.workspace }}/run.py