name: run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"  # 建议指定具体版本，如3.8/3.9/3.10

      - name: Install dependencies
        run: |
          pip install aiomysql selenium requests futures eventlet
          pip install -r requirements.txt  # 如果有requirements.txt也一并安装

      - name: Run run.py
        run: python ${{ github.workspace }}/run.py